export const CONSOLE_PERMISSIONS = {
  dashboardView: 'console.dashboard.view',
  applicationsView: 'console.applications.view',
  applicationsCreate: 'console.applications.create',
  applicationsEdit: 'console.applications.edit',
  applicationsDelete: 'console.applications.delete',
  applicationsResetSecret: 'console.applications.reset-secret',
  productsView: 'console.products.view',
  ordersView: 'console.orders.view',
  usersView: 'console.users.view',
  usersCreate: 'console.users.create',
  usersEdit: 'console.users.edit',
  usersDelete: 'console.users.delete',
  usersStatus: 'console.users.status',
  usersResetPassword: 'console.users.reset-password',
  usersForceLogout: 'console.users.force-logout',
  rolesView: 'console.roles.view',
  rolesCreate: 'console.roles.create',
  rolesEdit: 'console.roles.edit',
  rolesToggle: 'console.roles.toggle',
  rolesDelete: 'console.roles.delete',
  tagsView: 'console.tags.view',
  stickersView: 'console.stickers.view',
  systemConfigView: 'console.system-config.view',
  systemConfigCreate: 'console.system-config.create',
  systemConfigEdit: 'console.system-config.edit',
  systemConfigDelete: 'console.system-config.delete',
  hangfireView: 'console.hangfire.view',
} as const;

export type ConsolePermission = typeof CONSOLE_PERMISSIONS[keyof typeof CONSOLE_PERMISSIONS];
