export const CONSOLE_PERMISSIONS = {
  dashboardView: 'console.dashboard.view',
  applicationsView: 'console.applications.view',
  applicationsCreate: 'console.applications.create',
  applicationsEdit: 'console.applications.edit',
  applicationsDelete: 'console.applications.delete',
  applicationsResetSecret: 'console.applications.reset-secret',
  productsView: 'console.products.view',
  productsCreate: 'console.products.create',
  productsEdit: 'console.products.edit',
  productsDelete: 'console.products.delete',
  productsToggleSale: 'console.products.toggle-sale',
  ordersView: 'console.orders.view',
  ordersRetry: 'console.orders.retry',
  usersView: 'console.users.view',
  rolesView: 'console.roles.view',
  rolesCreate: 'console.roles.create',
  rolesEdit: 'console.roles.edit',
  rolesToggle: 'console.roles.toggle',
  rolesDelete: 'console.roles.delete',
  tagsView: 'console.tags.view',
  tagsCreate: 'console.tags.create',
  tagsEdit: 'console.tags.edit',
  tagsDelete: 'console.tags.delete',
  tagsRestore: 'console.tags.restore',
  tagsToggle: 'console.tags.toggle',
  tagsSort: 'console.tags.sort',
  stickersView: 'console.stickers.view',
  stickersCreate: 'console.stickers.create',
  stickersEdit: 'console.stickers.edit',
  stickersDelete: 'console.stickers.delete',
  stickersToggle: 'console.stickers.toggle',
  stickersSort: 'console.stickers.sort',
  stickersBatchUpload: 'console.stickers.batch-upload',
  systemConfigView: 'console.system-config.view',
  systemConfigCreate: 'console.system-config.create',
  systemConfigEdit: 'console.system-config.edit',
  systemConfigDelete: 'console.system-config.delete',
  hangfireView: 'console.hangfire.view',
} as const;

export type ConsolePermission = typeof CONSOLE_PERMISSIONS[keyof typeof CONSOLE_PERMISSIONS];
