//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radish.Auth.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radish.Auth.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 同意 的本地化字符串。
        /// </summary>
        internal static string auth_consent_allow {
            get {
                return ResourceManager.GetString("auth.consent.allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用： 的本地化字符串。
        /// </summary>
        internal static string auth_consent_client {
            get {
                return ResourceManager.GetString("auth.consent.client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        internal static string auth_consent_deny {
            get {
                return ResourceManager.GetString("auth.consent.deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 {0} 请求访问以下权限： 的本地化字符串。
        /// </summary>
        internal static string auth_consent_description {
            get {
                return ResourceManager.GetString("auth.consent.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权第三方访问你的 Radish 账号 的本地化字符串。
        /// </summary>
        internal static string auth_consent_heading {
            get {
                return ResourceManager.GetString("auth.consent.heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将被授予的权限： 的本地化字符串。
        /// </summary>
        internal static string auth_consent_scopes {
            get {
                return ResourceManager.GetString("auth.consent.scopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权确认 的本地化字符串。
        /// </summary>
        internal static string auth_consent_title {
            get {
                return ResourceManager.GetString("auth.consent.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用内置测试账号登录，后续可替换为实际用户体系。 的本地化字符串。
        /// </summary>
        internal static string auth_login_description {
            get {
                return ResourceManager.GetString("auth.login.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误，请重试。 的本地化字符串。
        /// </summary>
        internal static string auth_login_error_invalidCredentials {
            get {
                return ResourceManager.GetString("auth.login.error.invalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radish.Auth 测试登录 的本地化字符串。
        /// </summary>
        internal static string auth_login_heading {
            get {
                return ResourceManager.GetString("auth.login.heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string auth_login_passwordLabel {
            get {
                return ResourceManager.GetString("auth.login.passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string auth_login_submit {
            get {
                return ResourceManager.GetString("auth.login.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录成功，您现在可以关闭此页面或返回调用系统。 的本地化字符串。
        /// </summary>
        internal static string auth_login_success_message {
            get {
                return ResourceManager.GetString("auth.login.success.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试账号 的本地化字符串。
        /// </summary>
        internal static string auth_login_testAccount {
            get {
                return ResourceManager.GetString("auth.login.testAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码： 的本地化字符串。
        /// </summary>
        internal static string auth_login_testAccount_password {
            get {
                return ResourceManager.GetString("auth.login.testAccount.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名： 的本地化字符串。
        /// </summary>
        internal static string auth_login_testAccount_username {
            get {
                return ResourceManager.GetString("auth.login.testAccount.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radish 统一登录 的本地化字符串。
        /// </summary>
        internal static string auth_login_title {
            get {
                return ResourceManager.GetString("auth.login.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string auth_login_usernameLabel {
            get {
                return ResourceManager.GetString("auth.login.usernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已注销登录。 的本地化字符串。
        /// </summary>
        internal static string auth_logout_success {
            get {
                return ResourceManager.GetString("auth.logout.success", resourceCulture);
            }
        }
    }
}
