export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  CALLBACK: '/callback',
  APPLICATIONS: '/applications',
  PRODUCTS: '/products',
  ORDERS: '/orders',
  USERS: '/users',
  USER_DETAIL: '/users/:userId',
  ROLES: '/roles',
  ROLE_PERMISSIONS: '/roles/:roleId/permissions',
  CATEGORIES: '/categories',
  TAGS: '/tags',
  STICKERS: '/stickers',
  MODERATION: '/moderation',
  COINS: '/coins',
  EXPERIENCE: '/experience',
  STICKER_ITEMS: '/stickers/:groupId/items',
  SYSTEM_CONFIG: '/system-config',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  HANGFIRE: '/hangfire',
  THEME_TEST: '/theme-test',
} as const;
