#@Radish.Api_HostAddress = http://localhost:5165

### WeatherForecast
GET {{Api_HostAddress}}/api/WeatherForecast/Get
Accept: application/json
Authorization:Bearer {{JwtToken}}

### 获取全部用户
GET {{Api_HostAddress}}/api/User/GetUserList
Accept: application/json
Authorization:Bearer {{JwtToken}}

### 查询指定用户
GET {{Api_HostAddress}}/api/User/GetUserById/1
Accept: application/json
Authorization:Bearer {{JwtToken}}

### 获取租户下全部业务数据-字段隔离
GET {{Api_HostAddress}}/api/Tenant/BusinessTable
Accept: application/json
Authorization:Bearer {{JwtToken}}

### 获取租户下全部业务数据-表隔离
GET {{Api_HostAddress}}/api/Tenant/MultiBusinessTable
Accept: application/json
Authorization:Bearer {{JwtToken}}