name: radish_flutter
description: Radish Flutter Native client.
publish_to: none
version: 26.8.1+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.7
  flex_color_scheme: ^8.4.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
