name: radish_flutter
description: Radish Flutter Native client.
publish_to: none
version: 26.8.2+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  flex_color_scheme: ^8.4.0
  lucide_icons_flutter: 3.1.15
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/noto/licenses/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/noto/NotoSansSC-VF.ttf
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/noto/NotoSerifSC-VF.ttf
